# 使用数据库时代码自动创建的配置文件，从application.yml中可获取，不使用数据库时可删除该文件
spring:
  datasource:
    driver: oracle.jdbc.driver.OracleDriver
    type: com.zaxxer.hikari.HikariDataSource
    validation-query: SELECT 1 FROM DUAL
    url: jdbc:oracle:thin:@192.168.251.166:1521:orcl
    username: SHCH_POC
    password: SHCH_POC